on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule: [cron: "40 1 * * *"]

name: ci

jobs:
  # build, test all supported targets
  build-test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-gnu
        toolchain:
          - stable
            # msrv
          - 1.66.1

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.targets }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --workspace --target ${{ matrix.targets }}
      - run: cargo test --workspace --target ${{ matrix.targets }}

  # fmt and clippy on nightly builds
  fmt-clippy-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

